from django.urls import path

from . import views


urlpatterns = [
    path("health", views.health),
    path("auth/register", views.register),
    path("auth/login", views.login),
    path("auth/test", views.auth_test),
    path("upload", views.upload_file),
    path("spaces", views.spaces),
    path("spaces/<str:space_id>", views.space_detail),
    path("locations/suggest", views.location_suggestions),
    path("bookings", views.bookings),
    path("bookings/my", views.my_bookings),
    path("bookings/<int:booking_id>", views.booking_detail),
    path("users/search", views.search_users),
    path("users/profile", views.profile),
    path("users/profile/avatar", views.profile_avatar),
    path("users/updatepassword", views.update_password),
    path("users/<int:user_id>", views.public_profile),
    path("users/<int:user_id>/friends", views.user_friends),
    path("friends", views.friends_list),
    path("friends/request", views.send_friend_request),
    path("friends/respond", views.respond_friend_request),
    path("posts", views.posts),
    path("posts/<int:post_id>/like", views.toggle_like),
    path("posts/<int:post_id>/comments", views.add_comment),
    path("comments/<int:comment_id>/like", views.toggle_comment_like),
    path("posts/<int:post_id>", views.delete_post),
    path("groups", views.groups),
    path("groups/<int:group_id>", views.group_detail),
    path("groups/<int:group_id>/join", views.join_group),
    path("groups/<int:group_id>/messages", views.group_messages),
    path("groups/messages/<int:message_id>", views.message_detail),
    path("groups/messages/<int:message_id>/react", views.toggle_message_reaction),
    path("groups/<int:group_id>/members", views.group_members_list),
    path("groups/<int:group_id>/members/<int:target_user_id>", views.group_member_detail),
    path("groups/<int:group_id>/members/<int:target_user_id>/role", views.group_member_role),
    path("events", views.events),
    path("events/<str:event_id>", views.event_detail),
    path("events/<str:event_id>/register", views.register_event),
    path("events/<str:event_id>/participants", views.event_participants),
    path("events/<str:event_id>/participants/<int:target_user_id>/status", views.update_registration_status),
]
